# Site settings
title: 上海美襄信息科技有限公司
brief-intro: J2EE Server Engineer
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://frankdevhub-business.github.io" # the base hostname & protocol for your site

# other links
github_username:  frankdevhub-business
email: frankdevhub.business@gmail.com


# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# port
# port: 4000

# url
faq_dir: faq/
contact_dir: contact/
introduction_dir: introduction/


# excerpt
excerpt_separator: "\n\n\n\n"
